### ISSUE TITLE
tensorflow 2.0

### ISSUE THREAD

**Issue by burning846** [JiahuiYu/neuralgym#14]
When I run the code with tensorflow 2.0, it shows

> AttributeError: module tensorflow has no attribute contrib

and I find the bug is about tensorflow 2.0, so I wonder if the repo will be updated to follow the version of tensorflow.

**Comment by vutuanhai237** [comment]
Read this document: https://www.tensorflow.org/guide/upgrade#recommended_upgrade_process
It seems like one more error:
`AttributeError: module 'tensorflow' has no attribute 'get_variable_scope'`

**Comment by jhagege** [comment]
Hi, is anyone aware of a version that is working with TF 2.0

**Comment by csjunjun** [comment]
Hi, is anyone aware of a version that is working with TF 2.0

**Comment by jhagege** [comment]
> Hi, is anyone aware of a version that is working with TF 2.0

See https://github.com/JiahuiYu/neuralgym/pull/15
